const allVideosTypes = {
  GET_VIDEO_LIST_REQUEST: 'GET_VIDEO_LIST_REQUEST',
  GET_VIDEO_LIST_SUCCESS: 'GET_VIDEO_LIST_SUCCESS',
  GET_VIDEO_LIST_FAILURE:'GET_VIDEO_LIST_FAILURE',
};

export default allVideosTypes;
